# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Group Connection' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for Group Connection

  target 'Group ConnectionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Group ConnectionUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
